DROP DATABASE IF EXISTS Asiakas;
CREATE DATABASE Asiakas DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;
USE Asiakas
CREATE TABLE employee (
	id VARCHAR(20)NOT NULL PRIMARY KEY,
	firstName VARCHAR(40),
	lastName VARCHAR(40),
	address VARCHAR(100),
	phone VARCHAR(40),
	email VARCHAR(100)
)ENGINE=INNODB;
